name: Deploy Storybook

on:
  workflow_call

jobs:
  deploy-storybook:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write      
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # This step is to update internal dependencies specified via tag version to their latest available versions
      - name: Update dependencies
        run: npm ls --json |  jq -r '.dependencies | keys[]' | grep "@netcracker" | xargs --no-run-if-empty npm update
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}          

      - name: Build the showcase
        run: npm run build:showcase

      - name: Deploy Storybook to gh-pages        
        uses: peaceiris/actions-gh-pages@v4
        with:
          destination_dir: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-showcase
          keep_files: false

  on-delete:
    if: github.event_name == 'delete' && github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Delete corresponding folder in gh-pages branch
        run: |
          echo "Deleting folder ${{ github.event.ref }} from branch gh-pages"
          if [ -d ${{ github.event.ref }} ]; then            
            rm -rf ${{ github.event.ref }}
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git commit -m "docs: delete folder ${{ github.event.ref }} from gh-pages branch"
            git push origin gh-pages
          fi