name: Docker CI Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      file:
        required: true
        type: string
      context:
        required: true
        type: string
      platforms:
        required: true
        type: string
      labels:
        required: false
        type: string
    secrets:
      NPMRC:
        required: false
    outputs:
      image_tag:
        description: "Docker image tag of the published image."
        value: ${{ jobs.build_and_push_image.outputs.image_tag }}

env:
  REF_NAME: ${{ github.ref }}

jobs:
  build_and_push_image:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.prepare_tag.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Tag
        id: prepare_tag
        run: |
          TAG=$(echo ${REF_NAME} | sed 's@refs/tags/@@;s@refs/heads/@@;s@refs/pull/@pull/@;s@^develop$@dev@;s@^release$@next@;s@/@-@g;')
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          TIMESTAMP_TAG="timestamp-${TIMESTAMP}-${TAG}"
          echo "TAG=$TAG"
          echo "TIMESTAMP_TAG=$TIMESTAMP_TAG"
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "TIMESTAMP_TAG=$TIMESTAMP_TAG" >> $GITHUB_OUTPUT
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "GIT_HASH=$shortSha" >> $GITHUB_OUTPUT
          echo "GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          no-cache: true
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ghcr.io/netcracker/${{ inputs.name }}:${{ steps.prepare_tag.outputs.TAG }}
            ghcr.io/netcracker/${{ inputs.name }}:${{ steps.prepare_tag.outputs.TIMESTAMP_TAG }}
          provenance: false
          build-args: |
            GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
            TAG=${{ steps.prepare_tag.outputs.TAG }}
            GIT_HASH=${{ steps.extract_branch.outputs.GIT_HASH }}
            GIT_BRANCH=${{ steps.extract_branch.outputs.GIT_BRANCH }}
          labels: ${{ inputs.labels }}
          secrets: |
            "npmrc=${{ secrets.NPMRC }}"
