name: Deploy storybook

on:
  workflow_call:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check storybook exist
        id: check_script
        run: |
          if grep -q '"build:showcase":' package.json; then
            echo "::set-output name=has_script::true"
          fi

      - if: steps.check_script.outputs.has_script == 'true'
        name: Checkout gh-pages branch
        run: |
          git fetch origin
          git stash
          git checkout gh-pages

      - if: steps.check_script.outputs.has_script == 'true'
        name: Setup Pages
        uses: actions/configure-pages@v5

      - if: steps.check_script.outputs.has_script == 'true'
        name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./"

      - if: steps.check_script.outputs.has_script == 'true'
        name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4