name: Frontend CI Workflow
run-name: ${{ github.event_name == 'delete' && format('cleanup NPM dist tags') || format('') }}

on:
  workflow_call:

jobs:
  build-ci:
    uses: netcracker/qubership-apihub-ci/.github/workflows/fe-build-ci.yaml@feature/workflow-for-storybook
  test-ci:
    uses: netcracker/qubership-apihub-ci/.github/workflows/fe-test-ci.yaml@feature/workflow-for-storybook
  build-storybook-ci:
    uses: netcracker/qubership-apihub-ci/.github/workflows/fe-build-storybook-ci.yaml@feature/workflow-for-storybook
  deploy-storybook-ci:
    needs: build-storybook-ci
    uses: netcracker/qubership-apihub-ci/.github/workflows/fe-deploy-storybook-ci.yaml@feature/workflow-for-storybook
  on-delete:
    if: github.event_name == 'delete'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Get package name from package.json
        run: |
          if [ -f package.json ]; then
            PACKAGE_NAME=$(jq -r '.name' package.json)
            echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          else
            echo "No package.json found." && exit 1
          fi

      - name: Delete associated NPM dist tag
        run: |
          DELETED_BRANCH=${{ github.event.ref }}
          if [ "$DELETED_BRANCH" == "release" ]; then
            TAG_NAME="next"
          elif [ "$DELETED_BRANCH" == feature/* ]; then
            TAG_NAME="${CURRENT_BRANCH//\//-}"          
          fi          
          if [ -n "$TAG_NAME" ]; then            
            npm dist-tag rm "$PACKAGE_NAME" "$TAG_NAME"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
