name: Frontend CI Workflow
run-name: ${{ github.event_name == 'delete' && format('cleanup NPM dist tags') || format('') }}

on:
  workflow_call:
    outputs:
      npm_dist_tag:
        description: "NPM dist-tag of the published package."
        value: ${{ jobs.on-push.outputs.npm_dist_tag }}
      package_version:
        description: "NPM version of the published package."
        value: ${{ jobs.on-push.outputs.package_version }}      

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      npm_dist_tag: ${{ steps.publish.outputs.npm_dist_tag }}
      package_version: ${{ steps.get_version.outputs.package_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          registry-url: 'https://npm.pkg.github.com/'

      # This step is to update internal dependencies specified via tag version to their latest available versions
      - name: Update dependencies
        run:  |          
          npm ls --json |  jq -r '.dependencies | keys[]' | grep "@netcracker" | xargs --no-run-if-empty npm update
          cat ./package-lock.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
          
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate NPM dist tag
        id: calculate_npm_dist_tag
        run: |          
          CURRENT_BRANCH=$(echo ${{ github.event.ref }} | sed 's/refs\/heads\///')
          if [ "$CURRENT_BRANCH" == "release" ]; then
            NPM_DIST_TAG="next"
          elif [ "$CURRENT_BRANCH" == "develop" ]; then
            NPM_DIST_TAG="dev"
          elif [[ "$CURRENT_BRANCH" == refs/tags/* ]]; then
            NPM_DIST_TAG="latest"
          elif [[ "$CURRENT_BRANCH" != "main" ]]; then
            NPM_DIST_TAG="${CURRENT_BRANCH//\//-}"
          else
            NPM_DIST_TAG=''
          fi
          echo "NPM_DIST_TAG: $NPM_DIST_TAG"
          echo "npm_dist_tag=$NPM_DIST_TAG" >> $GITHUB_OUTPUT                  

      - name: Calculate prerelease suffix
        id: calculate_prerelease_suffix        
        run: |          
          NPM_DIST_TAG="${{ steps.calculate_npm_dist_tag.outputs.npm_dist_tag }}"
          if [ -n "$NPM_DIST_TAG" ] && [ "$NPM_DIST_TAG" != "latest" ]; then
            PRERELEASE_SUFFIX="$NPM_DIST_TAG"
          else
            PRERELEASE_SUFFIX=''
          fi
          echo "PRERELEASE_SUFFIX: $PRERELEASE_SUFFIX"
          echo "prerelease_suffix=$PRERELEASE_SUFFIX" >> $GITHUB_OUTPUT        

      - name: Check is Lerna project
        run: |
          if [ -f lerna.json ]; then
            echo "Project is a Lerna project."
            echo "IS_LERNA=true" >> $GITHUB_ENV
          else
            echo "Project is NOT a Lerna project."
            echo "IS_LERNA=false" >> $GITHUB_ENV
          fi

      - name: Bump version (dev branches only)        
        if: steps.calculate_prerelease_suffix.outputs.prerelease_suffix != ''
        run: |          
          # Get the current version and extract release part
          if [ "$IS_LERNA" == "true" ]; then
            CURRENT_VERSION=$(lerna list --json | jq -r '.[0].version')
          else
            CURRENT_VERSION=$(jq -r '.version' package.json)
          fi
          
          # Extract release part (remove any prerelease suffix if exists)
          RELEASE_VERSION=$(echo "$CURRENT_VERSION" | sed -E 's/(-[^+]+)?(\+[^+]+)?$//')
          
          # Generate timestamp in YYYYMMDDHHmmss format
          TIMESTAMP=$(date -u '+%Y%m%d%H%M%S')
          
          # Construct new version
          NEW_VERSION="${RELEASE_VERSION}-${{ steps.calculate_prerelease_suffix.outputs.prerelease_suffix }}.${TIMESTAMP}"
          
          echo "NEW_VERSION: $NEW_VERSION"
          
          # Set the new version
          if [ "$IS_LERNA" == "true" ]; then
            lerna version "${NEW_VERSION}" --no-git-tag-version --no-private --no-push --yes              
          else
            npm version "${NEW_VERSION}" --no-git-tag-version
          fi

      - name: Get package version
        id: get_version
        run: |
          if [ "$IS_LERNA" == "true" ]; then
            VERSION=$(lerna list --json | jq -r '.[0].version')
          else
            VERSION=$(jq -r '.version' package.json)
          fi
          echo "package_version=$VERSION" >> $GITHUB_OUTPUT
      
      # lerna won't publish packages with working directory changes
      - name: Commit changes (if any)                
        run: |
          # Check if there are any changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected. Preparing to commit."
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git commit -m "chore: bump prerelease version"            
          else
            echo "No changes to commit."
          fi

      - name: Build the package
        run: npm run build --if-present

      - name: Run tests
        run: npm test --if-present

      - name: Publish to GitHub NPM Registry
        id: publish
        if: steps.calculate_npm_dist_tag.outputs.npm_dist_tag != ''
        run: |
          if [ "$IS_LERNA" == "true" ]; then
            lerna publish from-package --yes --no-push --no-git-reset --no-git-tag-version --dist-tag ${{ steps.calculate_npm_dist_tag.outputs.npm_dist_tag }}  
          else
            npm publish --tag ${{ steps.calculate_npm_dist_tag.outputs.npm_dist_tag }}
          fi          
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

  on-delete:
    if: github.event_name == 'delete' && github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Calculate NPM dist tag
        id: calculate_npm_dist_tag
        run: |          
          CURRENT_BRANCH=$(echo ${{ github.event.ref }} | sed 's/refs\/heads\///')
          if [ "$CURRENT_BRANCH" == "release" ]; then
            NPM_DIST_TAG="next"
          elif [ "$CURRENT_BRANCH" == "develop" ]; then
            NPM_DIST_TAG="dev"
          elif [[ "$CURRENT_BRANCH" == refs/tags/* ]]; then
            NPM_DIST_TAG="latest"
          elif [[ "$CURRENT_BRANCH" != "main" ]]; then
            NPM_DIST_TAG="${CURRENT_BRANCH//\//-}"
          else
            NPM_DIST_TAG=''
          fi
          echo "NPM_DIST_TAG: $NPM_DIST_TAG"
          echo "npm_dist_tag=$NPM_DIST_TAG" >> $GITHUB_OUTPUT
      
      - name: Delete associated NPM dist tags
        if: steps.calculate_npm_dist_tag.outputs.npm_dist_tag != ''
        run: |
          # Get package names to process
          TAG_NAME=${{ steps.calculate_npm_dist_tag.outputs.npm_dist_tag }}
          if [ -f lerna.json ]; then
            echo "Detected Lerna project."
            PACKAGE_NAMES=$(lerna list --json | jq -r '.[].name')
          elif [ -f package.json ]; then
            echo "Detected single package npm project."
            PACKAGE_NAMES=$(jq -r '.name' package.json)
          else
            echo "No package.json or lerna.json found." && exit 1
          fi

          # Loop through all package names and remove tags
          for PACKAGE_NAME in $PACKAGE_NAMES; do
            echo "Processing package: $PACKAGE_NAME"
            if [ -n "$PACKAGE_NAME" ] && [ -n "$TAG_NAME" ]; then
              npm dist-tag rm "$PACKAGE_NAME" "$TAG_NAME"
            fi
          done
        env:        
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
